# Â©2022 Affectra AI
# ABOUT: Jekyll settings to auto generate demo website from this git repository.

# Site settings
title: Affectra Demo
email: info@affectra.ai
description: > 
  map the vibe anywhere & anytime  
  
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
#url: "http://webjeda.com" # the base hostname & protocol for your site

# Sidebar
default-image: logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.


# Footer
copyright:
   name: affectra.ai
   link: 'https://affectra.ai'


# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus: yes
disqus-shortname: webjeda-demo

# Social Media
linkedin: https://www.linkedin.com/company/quantumhood-ai/
github: https://github.com/Affectra-AI/demo.github.io/discussions
email: info@affectra.ai

#facebook like box
#fb-like-box: yes
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

